### PR TITLE
Add custom gulp tasks that can be combined with existing roboter tasks

### PR DESCRIPTION
**Pull request by joachimhb**
My use case was to add some steps in the bot release task, so after analyze+test-units but before checking git etc.

The useCustom function on the roboter has the same syntax as gulp.task(...), returns the instance so it can be chained.
taskNames must be prefixed with 'custom-' (Error if not), but there may be use cases to overwrite existing?

Example Usage:

````
const roboter = require('roboter');

roboter
  .workOn('server')
  .useCustom('custom-release', [], function(done) {
    runSequence(
      'analyze',
      'test-units',
      'unused-dependencies',
      'outdated',
      'custom-build',
      'custom-commit-dist',
      '_release-force',
      done
    );
  })
  .start();

// will allow: bot custom-release
````

What do you think?

### CODE REVIEW

**Comment by mattwagl** [comment]
Thanks for your input. I like the idea of specifing custom tasks as simple async functions. Just like the shell tasks it gives you the freedom to automate whatever you like inside your `roboter.js` file without adding more stuff to the core. 

Here are my initial thoughts/questions on this:

- Should we really follow the exact same syntax as `gulp.task`? In other words: Do we need the deps array as second parameter?
- Where does the `runSequence` function inside your code example come from? Will this be passed to the custom task as a paramter or do you require it from inside your `roboter.js` file?
- I'm not quite sure about the `custom-` prefix. I know this intended to prevent naming collisions but it feels a bit clunky having to type `bot custom-build`.
- I think there is [some additional stuff in this PR](https://github.com/thenativeweb/roboter/pull/24/commits/518a1938bb89980c32cceddb234502959a7a37d4) that should go into another PR.

Let's see what @goloroden is thinking once he's back from vacation.

**Comment by joachimhb** [comment]
Sorry about the other commit, was some previous commit or whatever, not used to this PR-thingy i guess :)

- The dependencies are not needed i guess, using runSequence there is no need
- Currently Im requirying it myself, i first thought to have 2 functions, addCustom and addCustomSequence, to keep the underlying modules on roboter side. But as i anyway use gulp for other tasks...
- With gulp 4 there is a way to retrieve the list of tasks already added, but with 3.x.x i thought having some kind of prefix would be fine to distinguish between roboter and custom tasks, a shorter prefix maybe for now?

But lets wait for golo and his thoughts on this :)

**Comment by goloroden** [comment]
I am currently on vacation, and since this is not a trivial one, I will get back to it once I am back. Please forgive the delay.

**Comment by goloroden** [comment]
So … finally, here's what I think. First of all, thanks a lot to @joachimhb for taking care of this issue :-)). This is awesome!

Instead of introducing the new `useCustom` function I'd prefer another option, which IMHO better integrates with the existing stuff. What about if we simply introduce a new `client/` namespace, in the same way as we also have `universal/`, `server/` and `client/`?

This basically could mean one could write code like this:

```javascript
roboter.
  workOn('server').
  equipWith(task => {
    task('client/foo', done => {
      // ...
    });
  }).
  start();
```

Inside of the callback function you can do whatever you want to, you only have to call `done` in the end. If you want to, you may use `runSequence` or something like that, but you also may use any other code.

IMHO this approach feels cleaner and integrates better with roboter's current approach.

What do you think?

**Comment by goloroden** [comment]
Resolved in 0.13.0, hence closed.

**Pull request closed without merging**
