### PR TITLE
fix for internal github

### PR DESCRIPTION
**Pull request by joachimhb**
Hi Golo,

I tested the following (because i did not want to update everything) tasks:

bot update --package [internal_module]
bot update --package [internal_module@0.0.2]

I will soon test more combinations, but i promised this pull request already for last week ;)

Regards,
Joachim

### CODE REVIEW

**Comment by goloroden** [comment]
Hi Joachim!

Basically, LGTM :-)
Thanks a lot for the improvements.

There is just one thing that I'm not sure about: Why did you replace the call to `doneEach1` by the more verbose syntax? Does this have any advantages?

Cheers,


Golo

**Comment by joachimhb** [comment]
Hi Golo,

i was struggling to find some error, therefore i added several debug-msgs, even inside the mentioned callback.
After that i just deleted the debug-msgs but the verbose syntax remained, sorry.

I just checked the error i was looking for back then (gulp formatError...), not sure if it's a good idea, but to have a more readable error output you could replace line 141 with:

return doneEach2({stack : `${errLsRemote} - Failed to list tags`});

Regards,
Joachim

**Comment by goloroden** [comment]
Okay, thanks for clarifying this :-)

Just one more thing: Could you please add yourself as contributor to the `package.json` file?

**Comment by joachimhb** [comment]
done :)

**Pull request merged**
